device.py: ensure file descriptors are closed
lorien/user_agent pull request #34
Opened 2021-07-24 07:46 UTC by immerrr

Out of curiosity I have upgraded python and run tests on one of my projects with `-W error` and one of the warnings that were reported were as follows:

```
  File "/home/immerrr/src/proj/venv/lib/python3.8/site-packages/user_agent/device.py", line 6, in <module>
    SMARTPHONE_DEV_IDS = json.load(open(os.path.join(
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/immerrr/src/proj/venv/lib/python3.8/site-packages/user_agent/data/smartphone_dev_id.json' mode='r' encoding='UTF-8'>

  File "/home/immerrr/src/proj/venv/lib/python3.8/site-packages/user_agent/device.py", line 8, in <module>
    TABLET_DEV_IDS = json.load(open(os.path.join(
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/immerrr/src/proj/venv/lib/python3.8/site-packages/user_agent/data/tablet_dev_id.json' mode='r' encoding='UTF-8'>
```

Here's a patch that should fix this.

2021-11-16 10:56 UTC, decaz requested changes

2021-11-16 10:56 UTC, decaz commented on user_agent/device.py
> +    SMARTPHONE_DEV_IDS = json.load(open(f))
@immerrr file is already opened so not `open(f)` but simply `f`.

2021-11-16 10:56 UTC, decaz commented on user_agent/device.py
> +    TABLET_DEV_IDS = json.load(open())
And here too.

2021-11-16 12:37 UTC, immerrr commented on user_agent/device.py
> +    TABLET_DEV_IDS = json.load(open())
Thanks, should be fixed now!

2021-11-16 13:39 UTC, decaz commented
@lorien can you merge it, please?

2021-12-04 10:34 UTC, lorien commented
@decaz please replace `f` variable with `inp` variable. I use single-char variables only in one-line or two-lines for cycles and list comprehensions.

2021-12-04 10:37 UTC, decaz commented
@immerrr take a look at https://github.com/lorien/user_agent/pull/34#issuecomment-986005886 please.

2021-12-04 13:42 UTC, lorien commented
Ok, nevermind, I'll just fix variables myself. Because in other case I can come back to this repo another half of year later :D

2021-12-04 13:42 UTC, merged

2021-12-04 13:53 UTC, decaz commented
@lorien thanks! Can you release a new version on PyPI please?

2021-12-04 13:57 UTC, immerrr commented
Thank you, @lorien :+1:

2021-12-04 14:01 UTC, lorien commented
@decaz yep, I've uploaded it to pypi